### ISSUE TITLE
inconsistent bit depth fails on libvips merge 

### ISSUE THREAD

**Issue by heynicejacket** [heynicejacket/dzi-builder#3]
If tiles don't all have the same bit depth, dzi_builder() returns the following error:

```
Traceback (most recent call last):
  File "C:/.../dzi-builder/dzi_builder/app.py", line 114, in <module>
    verbose=True
  File "C:/.../dzi-builder/dzi_builder/app.py", line 96, in dzi_builder
    combine_transparent_layer(layer_path, col, row, offset_right, offset_down_rect, vips_path, verbose)
  File "C:\...\dzi-builder\dzi_builder\core\vips.py", line 47, in combine_transparent_layer
    layer_png = make_columns(layer_path, rows_list, l, offset_down, vips_path, verbose=verbose)
  File "C:\...\dzi-builder\dzi_builder\core\vips.py", line 149, in make_columns
    os.rename(tile_path + current_output, tile_path + layer_output)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\...\\layers\\base-1.png' -> 'C:\\...\\layers\\base.png'
```

subprocess stdout returns the following error in debug on vips merge:

```
CompletedProcess(args='vips merge C:\\...\\layers\\base-row1tile2.png C:\\...\\layers\\base-row0tile2.png C:\\...\\layers\\base-0.png vertical 0 3000', returncode=1, stdout='', stderr='insert: images must have the same number of bands, or one must be single-band\n')
```

This error appeared when I had a background image in my Illustrator file's 'base' layer which was generated in Photoshop and that didn't match the dimension of the tiles. This was causing some tiles to be transparent and generated as 32 bit, and others to not be transparent and generated as 24 bit.

Removing that background image solves the problem, but obviously that's not ideal.

It doesn't seem that you can set the bit depth via Illustrator scripting.

**Comment by heynicejacket** [comment]
Upon further inspection, I didn't really understand PNG24 vs 32; the issue lies with the alpha channel in 32.

This [post](https://community.adobe.com/t5/photoshop/forcing-32-bit-png-export/td-p/10483072?page=1) on Adobe community support seems to imply that Illustrator automation doesn't allow to force an alpha channel, something backed up by the Illustrator scripting [documentation](https://www.adobe.com/devnet/illustrator/scripting.html).

The post suggests making a single pixel hole to create an alpha channel. This should work, and likely won't be noticeable in OpenSeadragon, as the default max zoom doesn't resolve 100% of the pixels.

Rather than have a user do this manually, I need to make this part of dzi-builder (directly before the tiles are combined).

Also see [lipvips issue #1525](https://github.com/libvips/libvips/issues/1525).

**Comment by heynicejacket** [comment]
This has been resolved by adding a vips composite loop to force-add an alpha channel to all images before merging.

Transparent and non-transparent layers can now be combined without issue.
